dai/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('web.urls') ),
    #url(r'^entradas/', include('web.urls')),
    #url(r'^area/', include('web.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', admin.site.urls),
    # /accounts,
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns.append(
        # /media/:<mixed>path/
        url(
            r'^media/(?P<path>.*)$',
            serve,
            kwargs={'document_root': settings.MEDIA_ROOT}))

web/urls.py
__author__ = 'Jose'
from django.conf.urls import include,url

from . import views

app_name = 'web'
urlpatterns = [

    url(r'^about/$', views.about, name='web.about'),
    # ex: /entrada/5/
    url(r'^entrada/(?P<entrada_id>[0-9]+)/$', views.entrada, name='entrada'),
    url(r'^actividad/(?P<actividad_id>[0-9]+)/$', views.actividad, name='actividad'),
    # ex: /area/Academicas/
    url(r'^area/Cultural/$', views.area_cultural, name='area'),
    url(r'^area/(?P<area>[a-zA-Z0-9]+)/$', views.area, name='area'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # ex: /entradas/
    url(r'^entradas/', views.index, name='index'),
    # /accounts,
    url(r'^accounts/', include('accounts.urls')),



    url(r'^contact/$', views.contact_view, name='web.contact'),
    url(r'^preguntas_frecuentes/$', views.faq_view, name='web.faq'),
    url(r'^politica_privacidad/$', views.politica_privacidad, name='web.politica_privacidad'),
    url(r'^$', views.index, name='index'),
]

web/templates/noticias/shorts/areas.html
{% load static %}
<link rel="stylesheet" href="{% static 'web/css/shorts/areas.css' %}" type="text/css" media="all">
<section id="gallery">
    <div id="botonesArea" >
        <ul>
            {% for area in areas %}
                {% if area.nombre == "Cultural" %}
                    <li ><a href="{% url 'web:area' area.nombre %}" title="{{ area.nombre }}"><span>{{ area.nombre }}</span></a></li>
                {% else %}
                    <li ><a href="{% url 'web:area' area.nombre %}" title="{{ area.nombre }}"><span>{{ area.nombre }}</span></a></li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
</section>