dai/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('web.urls') ),
    #url(r'^entradas/', include('web.urls')),
    #url(r'^area/', include('web.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', admin.site.urls),
    # /accounts,
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns.append(
        # /media/:<mixed>path/
        url(
            r'^media/(?P<path>.*)$',
            serve,
            kwargs={'document_root': settings.MEDIA_ROOT}))

web/urls.py
__author__ = 'Jose'
from django.conf.urls import include,url

from . import views

app_name = 'web'
urlpatterns = [

    url(r'^about/$', views.about, name='web.about'),
    # ex: /entrada/5/
    url(r'^entrada/(?P<entrada_id>[0-9]+)/$', views.entrada, name='entrada'),
    url(r'^actividad/(?P<actividad_id>[0-9]+)/$', views.actividad, name='actividad'),
    # ex: /area/Academicas/
    url(r'^area/Cultural/$', views.area_cultural, name='area'),
    url(r'^area/(?P<area>[a-zA-Z0-9]+)/$', views.area, name='area'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # ex: /entradas/
    url(r'^entradas/', views.index, name='index'),
    # /accounts,
    url(r'^accounts/', include('accounts.urls')),



    url(r'^contact/$', views.contact_view, name='web.contact'),
    url(r'^preguntas_frecuentes/$', views.faq_view, name='web.faq'),
    url(r'^politica_privacidad/$', views.politica_privacidad, name='web.politica_privacidad'),
    url(r'^$', views.index, name='index'),
]

web/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
import datetime

# region Users
#User.add_to_class('direccion', models.FloatField(null=True,blank=True))
#User.add_to_class('telefono', models.PositiveIntegerField(null=True,blank=True))
#User.add_to_class('amigos', models.ManyToManyField('self', symmetrical=True,  blank=True))
def user_str(self):
    return self.username

User.add_to_class('__str__',user_str)
# endregion

class Area(models.Model):
    nombre = models.CharField(max_length=50, unique= True)

    def __str__(self):
        return self.nombre

class Entrada(models.Model):
    titulo = models.CharField(max_length=100)
    noticia = RichTextField('Contenido de la noticia')
    resumen = RichTextField('Resumen de la noticia, para la pagina principal')
    id_area = models.ForeignKey(Area)
    id_usuario = models.ForeignKey(User)
    fecha = models.DateField(default=datetime.date.today)
    #imagen = models.ImageField(upload_to='/some/path',blank=True, null=True)

    def __str__(self):
        return self.titulo

    def typeClass(self):
        return 'Entrada'

    type = property(typeClass)

class Frases_celebres(models.Model):
    frase = models.CharField(max_length=300)
    autor = models.CharField(max_length=300)

class FAQ(models.Model):
    pregunta= models.CharField(max_length=300)
    respuesta = models.CharField(max_length=300)

# Semana cultural

class Evento(models.Model):
    titulo = models.CharField(max_length=100)

    def __str__(self):
        return self.titulo

class Actividad(models.Model):
    titulo = models.CharField(max_length=100)
    noticia = RichTextField('Contenido de la actividad')
    resumen = RichTextField('Resumen de la actividad, para la pagina principal')
    id_evento = models.ForeignKey(Evento)
    id_usuario = models.ForeignKey(User)
    fecha = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.titulo

    def typeClass(self):
        return 'Actividad'

    type = property(typeClass)

class Miembro(models.Model):
    nombre = models.CharField(max_length=100)
    area = models.CharField(max_length=100)
    descripcion = RichTextField('Contenido de la noticia')

    def __str__(self):
        return self.nombre

    def typeClass(self):
        return 'Miembro'

    type = property(typeClass)

web/templates/noticias/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- /#gallery -->
  <div class="main-box">
    <div class="container">
      <div class="inside">
        <div class="separator"></div>
            <!-- #gallery -->
            {% include "noticias/shorts/areas.html" %}
            <!-- /#gallery -->
        <div class="separator"></div>
        <div class="wrapper">
        	<!-- aside -->
          <aside>
            <h2>Sobre <span>Nuestra web</span></h2>
            <div class="img-box">
              En esta página web encontrarás mucha información de interés y paridas que posiblemente haya escrito jopegar, en su mayoria.
            </div>
            <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi.</p>
            Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto.
          </aside>
          <!-- content -->
          <section id="content">
            <article>
            	<h2>Sobre <span>Nuestro equipo</span></h2>
              <!-- .team-list -->
              <ul class="team-list">
                  {% for miembro in miembros %}
                    <li>
                     <h3>
                         <a href="#">{{ miembro.nombre}} - {{ miembro.area}}</a>
                         {% if user.is_staff %}
                            <a href="{% url 'accounts:accounts.modificarMiembro' miembro.id %}" class="modify">Modificar</a>
                         {% endif %}
                     </h3>
                        {% autoescape off %}
                            {{ miembro.descripcion }}
                        {% endautoescape %}
                    </li>

                  {% endfor %}
              </ul>
                {% if user.is_staff %}
                   <a href="{% url 'accounts:accounts.anadirMiembro' %}" class="anadirMiembro">Añadir</a>
                {% endif %}
              <!-- /.team-list -->
            </article>
          </section>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

web/templates/noticias/actividad.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="main-box">
    <div class="container">
      <div class="inside">
        <h2>{{entrada.titulo}}</h2>
        {% autoescape off %}
        <p>{{ entrada.noticia }}</p>
        {% endautoescape %}
        <h4>{{ entrada.fecha }}</h4>
        {% if user.is_staff %}
          <a href="{% url 'accounts:accounts.actividad' entrada.id %}"><div class="botonModificar">Modificar</div></a>
        {% endif %}
      </div>

      <div></div>
    </div>
  </div>
{% endblock content %}

web/templates/noticias/area.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="main-box">
    <div class="container">
      <div class="inside">
        <!-- .news -->
        <h2>{{area}}</h2>
            <ul class="news">
              {% for entrada in entradas %}
                <li>
                  <figure><strong>{{ entrada.fecha|date:"t" }}</strong>{{ entrada.fecha|date:"M" }}</figure>
                  <a href="{% url 'web:entrada' entrada.id %}"><h3>{{ entrada.titulo}}</h3>
                  {% autoescape off %}
                    {{ entrada.resumen }}
                  {% endautoescape %}</a>

                </li>

              {% endfor %}
            </ul>
            <!-- /.news -->
      </div>
    </div>
  </div>
{% endblock content %}

web/templates/noticias/area_cultural.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="main-box">
    <link rel="stylesheet" href="{% static 'web/css/area_cultural.css' %}" type="text/css" media="all">
      <div class="inside">
        <!-- .news -->
        <h2>Area cultural</h2>
        {% for evento in eventos %}
           <div class="actividades">
                <ul class="news tituloEvento"> <h3 class ="titulo">{{evento.titulo}} </h3>
                    {% for act in evento.actividad_set.all %}

                          <a href="{% url 'web:actividad' act.id %}">
                              <li><div class="titulo_act">{{act.titulo}}</div>
                                {% autoescape off %}
                                <div class="resumen">{{ act.resumen }}</div>
                                {% endautoescape %}</a>
                              </li>
                          </a>
                    {% endfor %}
            </ul>
              </div>
        {% endfor %}
      </div>
  </div>
{% endblock content %}

web/templates/noticias/contacts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- /#gallery -->
  <div class="main-box">
    <div class="container">
      <div class="inside">
        <div class="separator"></div>
            <!-- #gallery -->
            {% include "noticias/shorts/areas.html" %}
            <!-- /#gallery -->
        <div class="separator"></div>
        <div class="wrapper">
        	<!-- aside -->
          <aside>
            <h2>Como <span>contactar</span></h2>
            <!-- .contacts -->
            <ul class="contacts">
              <li><strong>Valencia:</strong>Valencia</li>
              <li><strong>Telf. 1:</strong>+34 666666666</li>
              <li><strong>Donde:</strong>Todo recto y a la derecha</li>
              <li><strong>Email:</strong><a href="#">maildedelegacion@upv.es</a></li>
            </ul>
            <!-- /.contacts -->
            <h3>Información:</h3>
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.
          </aside>
          <!-- content -->
          <section id="content">
            <article>
            	<h2>Otra zona de <span>Contacto</span></h2>
              Yep
            </article> 
          </section>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

web/templates/noticias/gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Gallery - Gallery Page | Design Company - Free Website Template from Templatemonster.com</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="css/reset.css" type="text/css" media="all">
  <link rel="stylesheet" href="css/style.css" type="text/css" media="all">
  <script type="text/javascript" src="js/jquery-1.4.2.min.js" ></script>
  <script type="text/javascript" src="js/cufon-yui.js"></script>
  <script type="text/javascript" src="js/Humanst521_BT_400.font.js"></script>
  <script type="text/javascript" src="js/Humanst521_Lt_BT_400.font.js"></script>
  <script type="text/javascript" src="js/cufon-replace.js"></script>
	<script type="text/javascript" src="js/roundabout.js"></script>
  <script type="text/javascript" src="js/roundabout_shapes.js"></script>
  <script type="text/javascript" src="js/gallery_init.js"></script>
  <script type="text/javascript" src="js/loopedslider.min.js"></script>
  <script type="text/javascript">
		$(function(){
			// Option set as a global variable
			$('#loopedSlider').loopedSlider({
				container: ".wrap",
				containerClick: false
			});
		});
	</script>
  <!--[if lt IE 7]>
  	<link rel="stylesheet" href="css/ie/ie6.css" type="text/css" media="all">
  <![endif]-->
  <!--[if lt IE 9]>
  	<script type="text/javascript" src="js/html5.js"></script>
    <script type="text/javascript" src="js/IE9.js"></script>
  <![endif]-->
</head>

<body>
  <!-- header -->
  <header>
    <div class="container">
    	<h1><a href="index.html">Design Company</a></h1>
      <nav>
        <ul>
        	<li><a href="index.html">Home</a></li>
          <li><a href="about.html">About</a></li>
          <li><a href="privacy.html">Privacy</a></li>
          <li><a href="gallery.html" class="current">Gallery</a></li>
          <li><a href="contacts.html">Contact</a></li>
          <li><a href="sitemap.html">Sitemap</a></li>
        </ul>
      </nav>
    </div>
	</header>
  <!-- #gallery -->
  <section id="gallery">
  	<div class="container">
    	<ul id="myRoundabout">
      	<li><img src="images/slide3.jpg" alt=""></li>
        <li><img src="images/slide2.jpg" alt=""></li>
        <li><img src="images/slide5.jpg" alt=""></li>
        <li><img src="images/slide1.jpg" alt=""></li>
        <li><img src="images/slide4.jpg" alt=""></li>
      </ul>
  	</div>
  </section>
  <!-- /#gallery -->
  <div class="main-box">
    <div class="container">
      <div class="inside">
        <div class="wrapper">
        	<!-- aside -->
          <aside>
            <h2>Template <span>Subpages</span></h2>
            <!-- loopedSlider begin -->
            <div id="loopedSlider">	
              <div class="wrap">
                <div class="slides">
                  <div><a href="#"><img src="images/thumb3.jpg" alt=""></a></div>
                  <div><a href="#"><img src="images/thumb2.jpg" alt=""></a></div>
                  <div><a href="#"><img src="images/thumb5.jpg" alt=""></a></div>
                  <div><a href="#"><img src="images/thumb1.jpg" alt=""></a></div>
                  <div><a href="#"><img src="images/thumb4.jpg" alt=""></a></div>
                </div>
              </div>
              <ul class="nav-controls">
              	<li><a href="#" class="previous">Previous Page</a></li>
              	<li><a href="#" class="next">Next Page</a></li>
              </ul>
            </div>
            <!-- loopedSlider end -->
          </aside>
          <!-- content -->
          <section id="content">
            <article>
            	<h2>About <span>Template</span></h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudansam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea tium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
              Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.
            </article> 
          </section>
        </div>
      </div>
    </div>
  </div>
  <!-- footer -->
  <footer>
    <div class="container">
    	<div class="wrapper">
        <div class="fleft">Copyright - Type in your name here</div>
        <div class="fright"><a rel="nofollow" href="http://www.templatemonster.com/" target="_blank">Website template</a> designed by TemplateMonster.com&nbsp; &nbsp; |&nbsp; &nbsp; <a href="http://templates.com/product/3d-models/" target="_blank">3D Models</a> provided by Templates.com</div>
      </div>
    </div>
  </footer>
  <script type="text/javascript"> Cufon.now(); </script>
</body>
</html>

web/templates/noticias/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'web/css/indexStyle.css' %}" type="text/css" media="all">
<div class="container">
    {% include "_messages.html" %}

</div><!-- /.container -->

<div class="main-box">
    <div class="container">
        <div class="inside">
            <div class="separator"></div>
            <!-- #gallery -->
            {% include "noticias/shorts/areas.html" %}
            <!-- /#gallery -->
            <div class="separator"></div>
            <div class="wrapper">
                <!-- aside -->
                <aside>
                    <h2>Noticias <span>Recientes</span></h2>
                    <!-- .news -->
                    <ul class="news">
                        {% for entrada in lista_ultimas_entradas %}
                        <li>
                            <figure><strong>{{ entrada.fecha|date:"d" }}</strong>{{ entrada.fecha|date:"M" }}</figure>
                            {% if entrada.typeClass == 'Entrada'  %}
                                 <a href="{% url 'web:entrada' entrada.id %}"><h3 class="titulo">{{ entrada.titulo}}</h3>
                            {% elif entrada.typeClass  == 'Actividad' %}
                                 <a href="{% url 'web:actividad' entrada.id %}"><h3 class="titulo">{{ entrada.titulo}}</h3>
                            {% endif %}
                                {% autoescape off %}
                                <div class="resumen">{{ entrada.resumen }}</div>
                                {% endautoescape %}</a>

                        </li>

                        {% endfor %}
                    </ul>
                    <!-- /.news -->
                </aside>
                <!-- content -->
                <section id="content">
                    <article>
                        <h2>Bienvenida a  <span>Delegación de Alumnos de Informática!</span></h2>

                        <p>Esta es nuestra página web, etc etc</p>
                        <figure><a href="#"><img src="{% static 'web/images/logo.jpg' %}" alt="" height="120" width="512"></a></figure>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                       ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex enderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </article>
                </section>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

web/templates/noticias/noticia.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="main-box">
    <div class="container">
      <div class="inside">
        <h2>{{entrada.titulo}}</h2>
        {% autoescape off %}
        <p>{{ entrada.noticia }}</p>
        {% endautoescape %}
        <h4>{{ entrada.fecha }}</h4>
        {% if user.is_staff %}
          <a href="{% url 'accounts:accounts.entrada' entrada.id %}"><div class="botonModificar">Modificar</div></a>
        {% endif %}
      </div>

      <div></div>
    </div>
  </div>
{% endblock content %}

web/templates/noticias/politica_privacidad.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <!-- TODO corregir texto y formato/estilo -->
    <div class="main-box">
      <div class="container">
        <div class="inside">
            <div class="separator"></div>
            <!-- #gallery -->
            {% include "noticias/shorts/areas.html" %}
            <!-- /#gallery -->
            <div class="separator"></div>
          <div class="wrapper">
            <h2> COOKIES </h2>
              <div style="margin-bottom: 10px">
                Las cookies son ficheros enviados a un navegador por medio de un servidor Web para registrar la navegación del Usuario en el Portal Web, cuando el Usuario permita su recepción, almacenado datos que podrán ser actualizados y recuperados.
                Las “cookies” utilizadas por el Portal Web de la Delegacion de Alumnos de Informatica, o el tercero que actúe en su nombre, se asocian únicamente con un Usuario anónimo y su ordenador, y no proporcionan por sí los datos personales del Usuario.
              </div>
              <h3>Los tipos de cookies se clasifican: </h3>

              <h5>Según su finalidad: </h5>
              <div style="margin-left: 10px">
                  <div style="margin: 0 0 10px 10px"><h6>Cookies técnicas:</h6> son aquellas imprescindibles y estrictamente necesarias para el correcto funcionamiento de un portal web y la utilización de las diferentes opciones y servicios que ofrece. Por ejemplo, las que sirven para el mantenimiento de la sesión, la gestión del tiempo de respuesta, rendimiento o validación de opciones, utilizar elementos de seguridad, compartir contenido con redes sociales, etc.
                  </div>

                  <div style="margin: 0 0 10px 10px"> <h6>Cookies de personalización: </h6> Éstas cookies permiten al usuario especificar o personalizar algunas características de las opciones generales del sitio web, por ejemplo, definir el idioma, configuración regional o tipo de navegador.
                  </div>
                  <div style="margin: 0 0 10px 10px"><h6>Cookies analíticas:</h6> Las cookies analíticas son las utilizadas por el portal web, para elaborar perfiles de navegación y poder conocer las preferencias de los usuarios del mismo para mejorar la oferta de productos y servicios. Por ejemplo, mediante una cookie analítica se controlarían las áreas geográficas de mayor interés de un usuario, cuál es el producto de más aceptación, etc.
                  </div>
                  <div style="margin: 0 0 10px 10px"><h6>Cookies publicitarias / de publicidad: </h6> Las cookies publicitarias permiten la gestión de los espacios publicitarios en base a criterios concretos. Por ejemplo la frecuencia de acceso, el contenido identidad, etc. Las cookies de publicidad permiten a través de la gestión de la publicidad almacenar información del comportamiento a través de la observación de hábitos estudiando los accesos y formando un perfil de preferencias del usuario, para ofrecer publicidad relacionada con los intereses de su perfil.
                  </div>
              </div>
              <h5>Según el plazo </h5>
              <div style="margin-left: 10px">
                <div style="margin: 0 0 10px 10px"><h6>Cookies de sesión: </h6> Las cookies de sesión son aquellas que duran en el tiempo que el usuario está navegando por la página web y se borran al finalizar.
                </div>
                <div style="margin: 0 0 10px 10px"><h6>Cookies persistentes: </h6> Éstas cookies quedan almacenadas al terminal del usuario, por un tiempo más largo, facilitando así el control de las preferencias escogidas sin tener que repetir ciertos parámetros cada vez que se visite el sitio web.
                Asimismo, dai.upv.es informa al usuario de que tiene la posibilidad de configurar su navegador de modo que se le informe de la recepción de cookies, pudiendo, si así lo desea, eliminarlas o impedir que sean instaladas en su disco duro a través del menú de configuración del mismo modificando los parámetros que generalmente se encuentran en “Opciones”, sección de “Privacidad” de cualquier navegador ( p.e.: Internet Explorer, Google Chrome, Firefos, Safari, Opera, …). Estos navegadores están sometidos a nuevas actualizaciones o modificaciones, por lo que se recomienda consultar la ayuda sobre cookies del navegador o las ayudas en línea de los desarrolladores.
                </br>Según lo dispuesto en el artículo 22.2 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), superyuppies.com informa de las cookies utilizadas en nuestro Portal Web son cookies de personalización.
                </br>Asimismo, dai.upv.es manifiesta de que la web puede contener enlaces de redes sociales (como Facebook o Twiter). informando de que no controla las cookies utilizadas por estas redes externas. Para más información sobre las cookies de redes sociales u otros sitios web ajenas, aconsejamos revisar sus propias políticas de cookies.
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

web/templates/noticias/preguntas_frecuentes.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- /#gallery -->
  <div class="main-box">
    <div class="container">
      <div class="inside">
          <div class="separator"></div>
            <!-- #gallery -->
            {% include "noticias/shorts/areas.html" %}
            <!-- /#gallery -->
            <div class="separator"></div>
        <div class="wrapper">
        	<h2>Te preguntaras algunas cosas.. es normal</h2>
            <h3> Aqui te daremos respuestas a las preguntas mas comunes</h3>
            <h4>FAQ</h4>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}