dai/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('web.urls') ),
    #url(r'^entradas/', include('web.urls')),
    #url(r'^area/', include('web.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', admin.site.urls),
    # /accounts,
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),

]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns.append(
        # /media/:<mixed>path/
        url(
            r'^media/(?P<path>.*)$',
            serve,
            kwargs={'document_root': settings.MEDIA_ROOT}))

web/urls.py
__author__ = 'Jose'
from django.conf.urls import include,url

from . import views

app_name = 'web'
urlpatterns = [

    url(r'^about/$', views.about, name='web.about'),
    # ex: /entrada/5/
    url(r'^entrada/(?P<entrada_id>[0-9]+)/$', views.entrada, name='entrada'),
    url(r'^actividad/(?P<actividad_id>[0-9]+)/$', views.actividad, name='actividad'),
    # ex: /area/Academicas/
    url(r'^area/Cultural/$', views.area_cultural, name='area'),
    url(r'^area/(?P<area>[a-zA-Z0-9]+)/$', views.area, name='area'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # ex: /entradas/
    url(r'^entradas/', views.index, name='index'),
    # /accounts,
    url(r'^accounts/', include('accounts.urls')),



    url(r'^contact/$', views.contact_view, name='web.contact'),
    url(r'^preguntas_frecuentes/$', views.faq_view, name='web.faq'),
    url(r'^politica_privacidad/$', views.politica_privacidad, name='web.politica_privacidad'),
    url(r'^$', views.index, name='index'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% static "web/images/" as url %}
<html lang="en">
<head>

  <title>Dai - Web</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="{% static 'web/css/reset.css' %}" type="text/css" media="all">
  <link rel="stylesheet" href="{% static 'web/css/cookiesStyle.css' %}" type="text/css" media="all">
  <link rel="stylesheet" href="{% static 'web/css/botones.css' %}" type="text/css" media="all">
  <link rel="stylesheet" href="{% static 'web/css/style.css' %}" type="text/css" media="all">
  <script type="text/javascript" src="{% static 'web/js/cookies.js' %}" ></script>
  <!--<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>-->
  <script type="text/javascript" src="{% static 'web/js/jquery-1.4.2.min.js' %}" ></script>
  <script type="text/javascript" src="{% static 'web/js/cufon-yui.js' %}"></script>
  <script type="text/javascript" src="{% static 'web/js/Humanst521_BT_400.font.js' %}"></script>
  <script type="text/javascript" src="{% static 'web/js/Humanst521_Lt_BT_400.font.js' %}"></script>
  <script type="text/javascript" src="{% static 'web/js/roundabout.js' %}"></script>
  <script type="text/javascript" src="{% static 'web/js/roundabout_shapes.js' %}"></script>
  <script type="text/javascript" src="{% static 'web/js/gallery_init.js' %}"></script>
  <script type="text/javascript" src="{% static 'web/js/cufon-replace.js' %}"></script>
  <!-- CKEDITOR -->
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
  <!--[if lt IE 7]>
  	<link rel="stylesheet" href="{% static 'web/css/ie/ie6.css' %}" type="text/css" media="all">
  <![endif]-->
  <!--[if lt IE 9]>
  	<script type="text/javascript" src="{% static 'web/js/html5.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/IE9.js' %}"></script>

  <![endif]-->
  <script>
    /*$(function(){
      var lastScrollTop = 0, delta = 75;
      $(window).scroll(function(event){
         var st = $(this).scrollTop();
         var b = false;
         if(Math.abs(lastScrollTop - st) <= delta)
            return;

         if (st > lastScrollTop && !b){
           b = true;
           $("header").addClass("sdown");
           $("#headerScroll").addClass("headerScroll");
         } else {
           b = false;
           $("header").removeClass("sdown");
           $("#headerScroll").removeClass("headerScroll");
         }
         lastScrollTop = st;
      });
    });*/

  </script>

</head>

<body onload="main()">
  <!-- header -->
  {% block header %}
  <header>
    <div class="container">
    	<h1><a href="{% url 'web:index' %}">DAI</a></h1>
      <nav>
        <ul id="headerScroll">
          <li><a href="{% url 'web:index' %}" >Home</a></li>
          <li><a href="{% url 'web:web.about' %}">Infórmate</a></li>
          <li><a href="http://www.pisado.es/pisado/">Pisados</a></li>
          <li><a href="https://www.dropbox.com/sh/m1slr3t6xyizzg2/AABAOQfgLFwMcYB3PBXh7pyca?dl=0">Exámenes</a></li>
          <li><a href="{% url 'web:web.faq' %}">Preguntas Frecuentes</a></li>
          <li><a href="{% url 'web:web.contact' %}">Contact</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:accounts.logout' %}">Logout</a></li>
            <li><a href="{% url 'accounts:accounts.panel' %}">{{ user.username }}</a></li>
          {% else %}
            <li><a href="{% url 'accounts:accounts.login' %}">Login</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
	</header>
  <div id="overbox3">
    <div id="infobox3">
        <p>Esta web utiliza cookies para obtener datos estadísticos de la navegación de sus usuarios. Si continúas navegando consideramos que aceptas su uso.
        <a href="{% url 'web:web.politica_privacidad' %}">Más información</a>
        <a onclick="aceptar_cookies();" style="cursor:pointer;">X Cerrar</a></p>
    </div>
  </div>
  {% endblock %}

{% block content %}{% endblock %}

{% block footer %}
  <!-- footer -->
  <footer>
    <div class="container">
    	<div class="wrapper">
        <div class="fleft" >Copyright - DAI UPV</div>
        <!--<div class="fright"><a rel="nofollow" href="http://www.templatemonster.com/" target="_blank">Website template</a> designed by TemplateMonster.com&nbsp; &nbsp; |&nbsp; &nbsp; <a href="http://templates.com/product/3d-models/" target="_blank">3D Models</a> provided by Templates.com</div>
        -->
      </div>
    </div>
  </footer>
  <script type="text/javascript"> Cufon.now(); </script>
</body>
</html>
{% endblock %}